[package]
org = "ballerina_examples"
name = "chat_memory_with_agent"
version = "0.1.0"
distribution = "2201.12.0"

[[dependency]]
org = "ballerinax"
name = "ai.memory.postgresql"
version = "1.0.0"
repository = "local"
